services:
  database:
    image: postgres:latest
    container_name: postgres_db
    hostname: postgresdb
    restart: always
    environment:
      POSTGRES_USER: home_crud
      POSTGRES_PASSWORD: home_crud
      POSTGRES_DB: home_crud
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata
volumes:
  pgdata:
    driver: local