services:
  postgres_db:
    image: postgres:latest
    container_name: postgres_db
    hostname: postgres_db
    environment:
      POSTGRES_USER: service
      POSTGRES_PASSWORD: service
      POSTGRES_DB: service
    ports:
      - "5432:5432"
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d
  service:
    build:
      dockerfile: Dockerfile
      context: .
    hostname: service
    ports:
      - "8080:8080"
    depends_on:
      - postgres_db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres_db:5432/service
      - POSTGRES_USER=service
      - POSTGRES_PASSWORD=service
    healthcheck:
      test: curl http://localhost:8080 || exit 0
      interval: 10s
      retries: 5
      start_period: 15s
      timeout: 10s