spring:
  application:
    name: rest
  datasource:
    hikari:
      jdbc-url: jdbc:postgresql://localhost:5432/home_crud
      username: home_crud
      password: home_crud
      driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/home_crud
  jpa:
    database: postgresql
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create
    open-in-view: false
  docker:
    compose:
      enabled: false
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
