spring:
  application:
    name: rest
  datasource:
    hikari:
      username: service
      password: service
      driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/service
  jpa:
    database: postgresql
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
  docker:
    compose:
      enabled: true
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
